# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BeerApp(object):
    def setupUi(self, BeerApp):
        BeerApp.setObjectName("BeerApp")
        BeerApp.resize(300, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(BeerApp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelIntro = QtWidgets.QLabel(BeerApp)
        self.labelIntro.setObjectName("labelIntro")
        self.verticalLayout.addWidget(self.labelIntro)
        self.labelCountry = QtWidgets.QLabel(BeerApp)
        self.labelCountry.setObjectName("labelCountry")
        self.verticalLayout.addWidget(self.labelCountry)
        self.countryComboBox = QtWidgets.QComboBox(BeerApp)
        self.countryComboBox.setObjectName("countryComboBox")
        self.verticalLayout.addWidget(self.countryComboBox)
        self.labelColor = QtWidgets.QLabel(BeerApp)
        self.labelColor.setObjectName("labelColor")
        self.verticalLayout.addWidget(self.labelColor)
        self.colorComboBox = QtWidgets.QComboBox(BeerApp)
        self.colorComboBox.setObjectName("colorComboBox")
        self.verticalLayout.addWidget(self.colorComboBox)
        self.labelTaste = QtWidgets.QLabel(BeerApp)
        self.labelTaste.setObjectName("labelTaste")
        self.verticalLayout.addWidget(self.labelTaste)
        self.tasteComboBox = QtWidgets.QComboBox(BeerApp)
        self.tasteComboBox.setObjectName("tasteComboBox")
        self.verticalLayout.addWidget(self.tasteComboBox)
        self.labelFiltered = QtWidgets.QLabel(BeerApp)
        self.labelFiltered.setObjectName("labelFiltered")
        self.verticalLayout.addWidget(self.labelFiltered)
        self.filteredComboBox = QtWidgets.QComboBox(BeerApp)
        self.filteredComboBox.setObjectName("filteredComboBox")
        self.verticalLayout.addWidget(self.filteredComboBox)
        self.labelFoam = QtWidgets.QLabel(BeerApp)
        self.labelFoam.setObjectName("labelFoam")
        self.verticalLayout.addWidget(self.labelFoam)
        self.foamComboBox = QtWidgets.QComboBox(BeerApp)
        self.foamComboBox.setObjectName("foamComboBox")
        self.verticalLayout.addWidget(self.foamComboBox)
        self.findButton = QtWidgets.QPushButton(BeerApp)
        self.findButton.setObjectName("findButton")
        self.verticalLayout.addWidget(self.findButton)

        self.retranslateUi(BeerApp)
        QtCore.QMetaObject.connectSlotsByName(BeerApp)

    def retranslateUi(self, BeerApp):
        _translate = QtCore.QCoreApplication.translate
        BeerApp.setWindowTitle(_translate("BeerApp", "ლუდის ამომრჩევი"))
        BeerApp.setStyleSheet(_translate("BeerApp", "\n"
"    QWidget {\n"
"        background-color: black;\n"
"        color: yellow;\n"
"        font: 12pt \"Arial\";\n"
"    }\n"
"    QLabel {\n"
"        color: yellow;\n"
"        font-weight: bold;\n"
"    }\n"
"    QComboBox {\n"
"        background-color: #333300;\n"
"        color: yellow;\n"
"        selection-background-color: yellow;\n"
"        selection-color: black;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: yellow;\n"
"        color: black;\n"
"        font-weight: bold;\n"
"        border-radius: 5px;\n"
"        padding: 6px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #ffff66;\n"
"    }\n"
"   "))
        self.labelIntro.setText(_translate("BeerApp", "აირჩიე ლუდის მახასიათებლები:"))
        self.labelCountry.setText(_translate("BeerApp", "ქვეყანა:"))
        self.labelColor.setText(_translate("BeerApp", "ფერი:"))
        self.labelTaste.setText(_translate("BeerApp", "გემო:"))
        self.labelFiltered.setText(_translate("BeerApp", "გაფილტვრა:"))
        self.labelFoam.setText(_translate("BeerApp", "ქაფის რაოდენობა:"))
        self.findButton.setText(_translate("BeerApp", "იპოვე ლუდი"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BeerApp = QtWidgets.QWidget()
    ui = Ui_BeerApp()
    ui.setupUi(BeerApp)
    BeerApp.show()
    sys.exit(app.exec_())
